services:
  mongodb:
    image: mongo:6-jammy
    container_name: attendance_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: attendance_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/attendance
      - PORT=5000
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: attendance_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  # NEW: Enterprise Monitoring Tools
  prometheus:
    image: prom/prometheus:latest
    container_name: attendance_prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: attendance_grafana
    ports:
      - "3005:3000" # Maps local 3005 to Grafana's internal 3000
    depends_on:
      - prometheus

volumes:
  mongo_data:
